# Generated by Django 4.0.3 on 2022-03-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('fabric_structure', models.CharField(max_length=50, verbose_name='Состав ткани')),
                ('material', models.CharField(max_length=50, verbose_name='Материал товара')),
                ('bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('novelties', models.BooleanField(default=True, verbose_name='Новинки')),
                ('title', models.CharField(max_length=50, verbose_name='Название коллекции')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('color', models.CharField(choices=[('BLA', 'Black'), ('WH', 'White'), ('RE', 'Red'), ('GR', 'Green'), ('YE', 'Yellow'), ('BLU', 'Blue'), ('OR', 'Orange'), ('GR', 'Grey')], max_length=100)),
                ('item_number', models.CharField(max_length=50, verbose_name='Артикул товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_range', models.CharField(max_length=50, verbose_name='Размерный ряд')),
                ('number_in_ruler', models.PositiveSmallIntegerField(verbose_name='Количество в линейке')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_number', to='product.product_item')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product_item')),
            ],
        ),
    ]
