# Generated by Django 4.0.3 on 2022-03-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('img', models.ImageField(upload_to='images', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('color_code', models.CharField(max_length=50, verbose_name='Код цвета')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('fabric_structure', models.CharField(max_length=50, verbose_name='Состав ткани')),
                ('bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('new_clothes', models.BooleanField(default=True, verbose_name='Новинки')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул товара')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('count_item', models.IntegerField(verbose_name='Количество вещей')),
                ('size', models.CharField(max_length=100, verbose_name='Размерный ряд')),
                ('material', models.CharField(max_length=50, verbose_name='Материал товара')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.collection')),
                ('color', models.ManyToManyField(to='product.productcolor')),
                ('cover_photo', models.ManyToManyField(to='product.productgallery', verbose_name='product_gallery')),
            ],
        ),
    ]
