# Generated by Django 4.0.3 on 2022-03-31 12:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=100, verbose_name='Размер скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранные'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=50, samples=None, verbose_name='Код цвета'),
        ),
    ]
