# Generated by Django 4.0.3 on 2022-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=100, verbose_name='Размер скидки'),
            preserve_default=False,
        ),
    ]
