# Generated by Django 4.0.3 on 2022-03-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название коллекции')),
                ('gender', models.CharField(max_length=5, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('size_range', models.CharField(max_length=50, verbose_name='Размерный ряд')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('number_in_ruler', models.PositiveSmallIntegerField(default=0, verbose_name='Количество в линейке')),
                ('item_number', models.CharField(max_length=50, verbose_name='Артикул товара')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_in_ruler',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_range',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1300, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
