# Generated by Django 4.0.3 on 2022-03-31 04:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=50, samples=None, verbose_name='Код цвета'),
        ),
    ]
