# Generated by Django 4.0.3 on 2022-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_discount_product_favorites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('date_registration', models.DateTimeField(auto_now=True)),
                ('status_order', models.CharField(choices=[('New', 'New'), ('Registration', 'Registration'), ('Cancel', 'Cancel')], default='New', max_length=50, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('count_item', models.IntegerField(default=1, verbose_name='Количество вещей')),
                ('size', models.CharField(max_length=100, verbose_name='Размерный ряд')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, verbose_name='Размер скидки')),
                ('color', models.ManyToManyField(to='product.productcolor')),
                ('img', models.ManyToManyField(to='product.productgallery', verbose_name='product_gallery')),
            ],
        ),
    ]
