# Generated by Django 4.0.3 on 2022-03-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product_item_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='Пол'),
        ),
    ]
