# Generated by Django 4.0.3 on 2022-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_userorder_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_item',
            field=models.IntegerField(default=1, verbose_name='Количество вещей'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
