# Generated by Django 4.0.3 on 2022-03-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcolor_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранные'),
        ),
    ]
