# Generated by Django 4.0.3 on 2022-04-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_count_item_delete_productorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
