# Generated by Django 4.0.3 on 2022-03-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_rename_about_us_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='header',
            new_name='title',
        ),
    ]
