# Generated by Django 4.0.3 on 2022-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
