# Generated by Django 4.0.3 on 2022-04-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_remove_cart_total_price_remove_cartitem_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Cart.cart'),
            preserve_default=False,
        ),
    ]
