# Generated by Django 4.0.3 on 2022-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('image2', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('image3', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
            ],
        ),
    ]
