# Generated by Django 4.0.3 on 2022-04-20 07:32

from django.db import migrations, models
import django.db.models.deletion
import others.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('image2', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('image3', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='BackCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Поле для имени')),
                ('number', models.CharField(max_length=200, verbose_name='Поле для номера')),
                ('backcall', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Тип обратный звонок')),
                ('data', models.DateTimeField(auto_now=True)),
                ('called', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Статус позвонили')),
            ],
        ),
        migrations.CreateModel(
            name='FloatingButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='Whatsapp номер')),
                ('link', models.URLField(max_length=100, verbose_name='Whatsapp ссылка')),
                ('telegram', models.URLField(max_length=100, verbose_name='Telegram ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images_footer', verbose_name='Логотип')),
                ('description', models.TextField(max_length=1500, verbose_name='Текстовая информация')),
                ('num', models.CharField(max_length=100, verbose_name='Номер в хедере')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Number', 'Number'), ('Gmail', 'Gmail'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('WhatsApp', 'Whatsapp')], max_length=100, verbose_name='Тип')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_help', verbose_name='Изображения')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_mainpage', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_news', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images_ouradvantages', validators=[others.validators.validate_file_extension], verbose_name='Изображение')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Helping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=300, verbose_name='Ответ')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='help', to='others.image')),
            ],
        ),
    ]
