# Generated by Django 4.0.3 on 2022-04-20 09:10

from django.db import migrations, models
import django.db.models.deletion
import others.models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHelping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name=others.models.Helping)),
            ],
        ),
        migrations.AlterField(
            model_name='helping',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImageHelping', to='others.imagehelping'),
        ),
    ]
