# Generated by Django 4.0.3 on 2022-03-31 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_aboutus_news_delete_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_help', verbose_name='Изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=300, verbose_name='Ответ')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='help', to='others.image')),
            ],
        ),
    ]
