# Generated by Django 4.0.3 on 2022-03-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_image_help'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Help',
            new_name='Helping',
        ),
    ]
