# Generated by Django 4.0.3 on 2022-04-01 09:25

from django.db import migrations, models
import others.validators


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_mainpage_ouradvantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouradvantages',
            name='icon',
            field=models.ImageField(upload_to='images_ouradvantages', validators=[others.validators.validate_file_extension], verbose_name='Изображение'),
        ),
    ]
