# Generated by Django 4.0.3 on 2022-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='phone',
        ),
        migrations.AddField(
            model_name='footer',
            name='phone1',
            field=models.CharField(default=1, max_length=20, verbose_name='Номера телефона 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номера телефона 2'),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номера телефона 3'),
        ),
    ]
