# Generated by Django 4.0.3 on 2022-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_remove_footer_phone_footer_phone1_footer_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.IntegerField(default='whatsapp.com/', max_length=100, verbose_name='Whatsapp номер')),
                ('telegram', models.URLField(verbose_name='Telegram ссылка')),
            ],
        ),
    ]
