# Generated by Django 4.0.3 on 2022-04-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_alter_floatingbutton_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone3',
        ),
        migrations.AlterField(
            model_name='footer',
            name='num',
            field=models.CharField(max_length=100, verbose_name='Номер в хедере'),
        ),
        migrations.CreateModel(
            name='NumberForFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='others.footer')),
            ],
        ),
    ]
