# Generated by Django 4.0.3 on 2022-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0012_remove_footer_phone1_remove_footer_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Поле для имени')),
                ('number', models.CharField(max_length=200, verbose_name='Поле для номера')),
                ('backcall', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Тип обратный звонок')),
                ('data', models.DateTimeField(auto_now=True)),
                ('called', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Статус позвонили')),
            ],
        ),
    ]
