# Generated by Django 4.0.3 on 2022-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0013_backcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingbutton',
            name='link',
            field=models.URLField(default=1, max_length=100, verbose_name='Whatsapp ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floatingbutton',
            name='telegram',
            field=models.URLField(max_length=100, verbose_name='Telegram ссылка'),
        ),
        migrations.AlterField(
            model_name='floatingbutton',
            name='whatsapp',
            field=models.CharField(max_length=100, verbose_name='Whatsapp номер'),
        ),
    ]
