# Generated by Django 4.0.3 on 2022-04-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0014_floatingbutton_link_alter_floatingbutton_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
