# Generated by Django 4.0.3 on 2022-04-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('date_registration', models.DateTimeField(auto_now=True)),
                ('status_order', models.CharField(choices=[('New', 'New'), ('Registration', 'Registration'), ('Cancel', 'Cancel')], default='New', max_length=50, verbose_name='Статус заказа')),
            ],
        ),
    ]
